# Generated by Django 4.0.4 on 2022-05-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(default='', max_length=6)),
                ('email', models.CharField(default='', max_length=50)),
                ('aadhar', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
