# Generated by Django 4.0.4 on 2022-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_appointmentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='Time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
